# Generated by Django 3.1.7 on 2021-05-23 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipmentPrice',
            new_name='shippingPrice',
        ),
    ]
