# Generated by Django 3.1.7 on 2021-05-24 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_shippingaddress_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='postalCode',
            new_name='phone',
        ),
    ]
