# Generated by Django 3.1.7 on 2021-05-31 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20210530_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='message',
            field=models.CharField(blank=True, default='Order in progress', max_length=200, null=True),
        ),
    ]
