const products = [
    {
        '_id':'1',
        'name': 'Car item for sale do check',
        'image': '/images/1.jpg',
        'description': 'asdjsadj aksjd asdl asld laskdlas dlas d d kasldk alsk laskd laskl ask lasdlas kdl',
        'brand' : 'sdskdj',
        'category' : 'body',
        'price' : 80.99,
        'countInStock' : 0,
        'rating' : 4.5,
        'numReviews': 12,
    },
    {
        '_id':'2',
        'name': 'dsd item for sale do check',
        'image': '/images/2.jpg',
        'description': 'asdjsadj aksjd asdl asld laskdlas dlas d d kasldk alsk laskd laskl ask lasdlas kdl',
        'brand' : 'sdskdj',
        'category' : 'body',
        'price' : 230.99,
        'countInStock' : 120,
        'rating' : 5.5,
        'numReviews': 22,
    },
    {
        '_id':'3',
        'name': 'dfgr item for sale do check',
        'image': '/images/3.jpg',
        'description': 'asdjsadj aksjd asdl asld laskdlas dlas d d kasldk alsk laskd laskl ask lasdlas kdl',
        'brand' : 'sdskdj',
        'category' : 'tyre',
        'price' : 803.99,
        'countInStock' : 130,
        'rating' : 3.5,
        'numReviews': 32,
    },
    {
        '_id':'4',
        'name': 'C444ar item for sale do check',
        'image': '/images/4.jpg',
        'description': 'asd444jsadj aksjd asdl asld laskdlas dlas d d kasldk alsk laskd laskl ask lasdlas kdl',
        'brand' : 'sdskdj',
        'category' : 'front',
        'price' : 40.99,
        'countInStock' : 40,
        'rating' : 4.4,
        'numReviews': 42,
    },
    {
        '_id':'5',
        'name': 'C5555ar item for sale do check',
        'image': '/images/5.jpg',
        'discription': 'asd555jsadj aksjd asdl asld laskdlas dlas d d kasldk alsk laskd laskl ask lasdlas kdl',
        'brand' : 'sds55kdj',
        'category' : 'back',
        'price' : 850.99,
        'countInStock' : 105,
        'rating' : 2.5,
        'numReviews': 152,
    },
    {
        '_id':'6',
        'name': 'C6666ar item for sale do check',
        'image': '/images/6.jpg',
        'discription': 'asd6666jsadj aksjd asdl asld laskdlas dlas d d kasldk alsk laskd laskl ask lasdlas kdl',
        'brand' : 'sds66kdj',
        'category' : 'back',
        'price' : 860.99,
        'countInStock' : 160,
        'rating' : 4.6,
        'numReviews': 62,
    },
]
export default products